    # NumPy – Numerical Python
## 1. Why Learn NumPy?

#### What is it?

NumPy is a powerful Python library for numerical computations. It provides fast and memory-efficient multi-dimensional arrays.

#### Why we need it?

1.Pure Python lists are slow for large datasets.

2.NumPy arrays are optimized for speed and vectorized operations.

3.Most Data Science & Machine Learning libraries (like Pandas, Scikit-Learn, TensorFlow) are built on top of NumPy.

#### Where is it used?

1.Data Analysis

2.Machine Learning & Deep Learning

3.Image Processing (OpenCV, PIL use NumPy arrays)

5.Scientific Computing & Simulations

In [ ]:
import numpy as np

# Arrays vs Python Lists

In [6]:
## 2. Importing NumPy
import numpy as np

## 3. Arrays vs Python Lists
import numpy as np
import time

# Python list
py_list = [i for i in range(1000000)]

# NumPy array
np_array = np.arange(1000000)

# Time comparison
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)


Python list sum time: 0.008610725402832031
NumPy array sum time: 0.0010685920715332031


In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Creating Arrays

In [2]:
# From list 
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Zeros and Ones
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))

# Range and Linspace
print("Arange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))

Array: [1 2 3 4 5]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [3]:
## 5. Array Properties

arr = np.array([[1,2,3],[4,5,6]])
print("Array shape:", arr.shape)
print("Array dtype:", arr.dtype)
print("Array size:", arr.size)
print("Array ndim:", arr.ndim)

Array shape: (2, 3)
Array dtype: int64
Array size: 6
Array ndim: 2


In [17]:
## 6. Indexing
arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])
# ----------------------
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements at indices 0, 2, 4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix dtype: int64
Matrix size: 9
Matrix ndim: 2
2
[4 5 6]
[3 6 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [9]:
## 7. Operations and Broadcasting
a = np.array([1,2,3]) 
b = np.array([4,5,6])
print("a + b:", a + b)            # Element-wise addition
print("a * b:", a * b)            # Element-wise multiplication
print("a + 10:", a + 10)          # Broadcasting
print("a * 2:", a * 2)            # Broadcasting

a + b: [5 7 9]
a * b: [ 4 10 18]
a + 10: [11 12 13]
a * 2: [2 4 6]


In [15]:
## 8. Mathematical Functions
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [11]:
## 9. Reshaping Arrays
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
arr=np.arange(1,10)
reshaped=arr.reshape((3,3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print("printing matrix")
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Extracting row2")
print(mat[1,:])

printing matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Extracting row2
[4 5 6]


In [38]:
#3.Find the mean, median, and standard deviation of [12, 15, 20, 25, 30].
a=np.array([12,15,20,25,30])
avg=np.mean(a)
med=np.median(a)
sd=np.std(a)
print("Array:")
print(a)
print("Mean of the array:",avg)
print("Median of the array:",med)
print("Standard Deviation of the array:",sd)

Array:
[12 15 20 25 30]
Mean of the array: 20.4
Median of the array: 20.0
Standard Deviation of the array: 6.529931086925803


In [36]:
#4.Generate a random 5×5 matrix and find its maximum and minimum values.(Hint: Use np.random.rand for random numbers)
rm=np.random.rand(5,5)
print("Random Matrix:",rm)
print("Maximum Value:",np.max(rm))
print("Minimum Value:",np.min(rm))

Random Matrix: [[0.23357277 0.57334175 0.30438276 0.59688952 0.34501321]
 [0.65296709 0.30621198 0.12243467 0.83122897 0.39845267]
 [0.85578817 0.66806572 0.21760763 0.09871044 0.93802576]
 [0.94489212 0.59197089 0.11098857 0.67116322 0.84539123]
 [0.55927348 0.12859183 0.61789864 0.27672065 0.84831525]]
Maximum Value: 0.9448921165470237
Minimum Value: 0.09871043949959268
